name: social_auth_buttons
description: Social Auth Buttons is a fork of auth_buttons flutter widget library. It includes buttons for authenticating with the most popular social networks and with email/password.
version: 2.0.0
homepage: https://github.com/TheFe91/flutter_auth_buttons

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.21.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/social_auth_buttons/images/google_logo.svg
    - packages/social_auth_buttons/images/facebook_logo_blue.svg
    - packages/social_auth_buttons/images/facebook_logo_white.svg
    - packages/social_auth_buttons/images/apple_logo_black.svg
    - packages/social_auth_buttons/images/apple_logo_white.svg
    - packages/social_auth_buttons/images/twitter_logo_black.svg
    - packages/social_auth_buttons/images/twitter_logo_white.svg
    - packages/social_auth_buttons/images/github_logo_black.svg
    - packages/social_auth_buttons/images/github_logo_white.svg
    - packages/social_auth_buttons/images/microsoft_logo.svg
    - packages/social_auth_buttons/images/envelope_logo_white.svg
    - packages/social_auth_buttons/images/envelope_logo_black.svg
